# BEIREK Content Scout - News Sources (Verified RSS)
# ===================================================
# Only verified working RSS feeds
# Last updated: 2026-01-31

sources:
  # ===========================================================================
  # PRIMARY SOURCES - High quality, verified working
  # ===========================================================================
  primary:
    # --- Solar Energy ---
    - name: "PV Magazine"
      url: "https://www.pv-magazine.com"
      rss_url: "https://www.pv-magazine.com/feed/"
      category: "solar"
      priority: 1

    - name: "Solar Power World"
      url: "https://www.solarpowerworldonline.com"
      rss_url: "https://www.solarpowerworldonline.com/feed/"
      category: "solar"
      priority: 1

    - name: "PV Tech"
      url: "https://www.pv-tech.org"
      rss_url: "https://www.pv-tech.org/feed/"
      category: "solar"
      priority: 1

    # --- Wind Energy ---
    - name: "Windpower Monthly"
      url: "https://www.windpowermonthly.com"
      rss_url: "https://www.windpowermonthly.com/rss"
      category: "wind"
      priority: 1

    - name: "Offshore Wind"
      url: "https://www.offshorewind.biz"
      rss_url: "https://www.offshorewind.biz/feed/"
      category: "wind"
      priority: 1

    # --- Energy Storage ---
    - name: "Energy Storage News"
      url: "https://www.energy-storage.news"
      rss_url: "https://www.energy-storage.news/feed/"
      category: "storage"
      priority: 1

    # --- General Energy ---
    - name: "Utility Dive"
      url: "https://www.utilitydive.com"
      rss_url: "https://www.utilitydive.com/feeds/news/"
      category: "energy"
      priority: 1

    - name: "Renewable Energy World"
      url: "https://www.renewableenergyworld.com"
      rss_url: "https://www.renewableenergyworld.com/feed/"
      category: "energy"
      priority: 1

    - name: "CleanTechnica"
      url: "https://cleantechnica.com"
      rss_url: "https://cleantechnica.com/feed/"
      category: "energy"
      priority: 1

    - name: "Electrek"
      url: "https://electrek.co"
      rss_url: "https://electrek.co/feed/"
      category: "energy"
      priority: 1

    # --- Grid & Power ---
    - name: "Power Engineering"
      url: "https://www.power-eng.com"
      rss_url: "https://www.power-eng.com/feed/"
      category: "grid"
      priority: 1

  # ===========================================================================
  # SECONDARY SOURCES - Specialized topics
  # ===========================================================================
  secondary:
    # --- Project Finance & Development ---
    - name: "Infrastructure Investor"
      url: "https://www.infrastructureinvestor.com"
      rss_url: "https://www.infrastructureinvestor.com/feed/"
      category: "finance"
      priority: 2

    - name: "Bloomberg NEF"
      url: "https://about.bnef.com"
      rss_url: "https://about.bnef.com/feed/"
      category: "finance"
      priority: 2

    - name: "Development Finance"
      url: "https://www.developmentfinance.com"
      rss_url: "https://www.developmentfinance.com/feed/"
      category: "finance"
      priority: 2

    - name: "Guardian Global Development"
      url: "https://www.theguardian.com/global-development"
      rss_url: "https://www.theguardian.com/global-development/rss"
      category: "finance"
      priority: 2

    # --- Hydrogen ---
    - name: "H2 View"
      url: "https://www.h2-view.com"
      rss_url: "https://www.h2-view.com/feed/"
      category: "hydrogen"
      priority: 2

    - name: "Hydrogen Fuel News"
      url: "https://www.hydrogenfuelnews.com"
      rss_url: "https://www.hydrogenfuelnews.com/feed/"
      category: "hydrogen"
      priority: 2

    # --- ESG ---
    - name: "ESG Today"
      url: "https://www.esgtoday.com"
      rss_url: "https://www.esgtoday.com/feed/"
      category: "esg"
      priority: 2

    # --- Construction ---
    - name: "Construction Dive"
      url: "https://www.constructiondive.com"
      rss_url: "https://www.constructiondive.com/feeds/news/"
      category: "construction"
      priority: 2

  # ===========================================================================
  # TERTIARY SOURCES - Backup
  # ===========================================================================
  tertiary: []

# Source categories
categories:
  solar: "Solar energy projects and technology"
  wind: "Wind energy (onshore/offshore)"
  storage: "Energy storage (BESS)"
  grid: "Grid modernization and transmission"
  energy: "General renewable energy"
  finance: "Project finance and investment"
  hydrogen: "Hydrogen and green fuels"
  construction: "EPC and construction"
  esg: "ESG and sustainability"
